### ISSUE TITLE
Open-bolt weapons kinda borked.

### ISSUE THREAD

**Issue by Jayrazer** [HaodongMo/arc9_fas2#5]
Upon shooting for the first time, entering and exiting sights as well as exiting the customize menu plays the firing sound and recoils the screen as if a shot has been fired.  Tactical reloads become impossible too, only empty reloads can be performed.

https://user-images.githubusercontent.com/79886161/211131800-7c8ae5e1-c9bc-4588-ba97-292692147fb2.mp4

**Comment by Jayrazer** [comment]
Update: This seems to be an issue with all open-bolt weapons.

https://user-images.githubusercontent.com/79886161/211158604-fa9c25a8-23b4-4742-8407-966f16e26407.mp4

**Comment by necoarctic** [comment]
this is a problem with ARC9 itself and has been fixed in the github build
